# Example configuration
import: [file, firebase, $: utils]

config:
  firebase:
    keyFilename: posts/firebase.json
    databaseURL: https://modulo-one.firebaseio.com

events:
  # - watch: file 'posts/:postId/content.md'
  #   on [add, change]: file.readFile >> firebase.set 'postContent/:postId'
  #   on [unlink]: $.partial firebase.remove, 'postContent/:postId'
  - watch: file 'posts/:postId/content.md'
    on [add, change]: file.readFile >> $.partial file.writeFile, 'posts/asd/content2.md'
    on [unlink]: $.partial firebase.unlink, 'posts/:postId/content2.md'
