# Example configuration
plugins:
  firebase:
    keyFilename: posts/firebase.json
    databaseURL: https://modulo-one.firebaseio.com

events:
  - on file [add, change]: posts/:postId/content.md
    do file [writeFile]: posts/:postId/content-copy.md

  - on file [unlink]: posts/:postId/content.md
    do file [unlink]: posts/:postId/content-copy.md
