language: node_js

node_js: 6

branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
  global:
    - GCS_PROJECT_ID=mock
    - GCS_BUCKET=mock

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
